language: node_js
sudo: false
node_js:
  - '5.0.0'
notifications:
  email: false
before_script:
  - npm install -g karma-cli
  - npm install -g grunt-cli
script:
  - grunt ci --stack
cache:
  directories:
    - node_modules
