language: node_js
sudo: false
node_js:
- '0.10'
notifications:
  email: false
before_script:
  - npm install -g karma-cli
  - npm install -g grunt-cli
script:
  - npm run-script citest
cache:
  directories:
    - node_modules
